version: "3"

services:
  portainer:
    container_name: portainer
    # image: portainer/portainer-ce
    build: .
    ports:
     - "8000:8000"
     - "9000:9000"
#    environment:
#      TZ: 'Europe/London'
    # Volumes store your data between container upgrades
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data:/data'
    restart: unless-stopped
#    network_mode: host
